// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6l0xwAy_C_lZhNJUKHriKJFA5Oo8I0Pc',
    appId: '1:39806899636:web:67ef2dda01f2fd323d0ee1',
    messagingSenderId: '39806899636',
    projectId: 'firebase-examples-12423512315',
    authDomain: 'fir-examples-12423512315.firebaseapp.com',
    storageBucket: 'firebase-examples-12423512315.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUM7qPLl07QbXH8kq4-Gx1jQLQzZw1n5o',
    appId: '1:39806899636:android:0f9cfcdd9ddaf61c3d0ee1',
    messagingSenderId: '39806899636',
    projectId: 'firebase-examples-12423512315',
    storageBucket: 'firebase-examples-12423512315.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE6i5EmrfcpA3hTVdgraItVn5-jTy8DPk',
    appId: '1:39806899636:ios:3cea8913256ced573d0ee1',
    messagingSenderId: '39806899636',
    projectId: 'firebase-examples-12423512315',
    storageBucket: 'firebase-examples-12423512315.appspot.com',
    iosClientId: '39806899636-k81mjg1m870jmcppkinngs3sne4cpmlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.csc315TermProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE6i5EmrfcpA3hTVdgraItVn5-jTy8DPk',
    appId: '1:39806899636:ios:3cea8913256ced573d0ee1',
    messagingSenderId: '39806899636',
    projectId: 'firebase-examples-12423512315',
    storageBucket: 'firebase-examples-12423512315.appspot.com',
    iosClientId: '39806899636-k81mjg1m870jmcppkinngs3sne4cpmlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.csc315TermProject',
  );
}
